build:
    build_starting:
        image: python:2
        commands:
            - echo "Beginning new build"
    run_tests:
        image: python:2-alpine
        commands:
            - pip install -r requirements.txt
            - python testing.py

publish:
    docker:
        repo: kriswans/cicd_demoapp
        tag: latest
        username: kriswans
        password: S0com123!
        email: kris@swannynet.com

deploy:
    webhook:
        image: plugins/drone-webhook
        skip_verify: true
        method: POST
        auth:
            username: CICD1
            password: CICD1
        urls:
            - https://control.sandbox.imapex.io/marathon/v2/apps/class/kriswans/restart?force=true

notify:
    spark:
        image: hpreston/drone-spark
        auth_token: ZTYyYTQ2ZmItMWU1OS00MzhiLTliMTYtYzAwODc0OTUxODc0ZDdkODM0NDYtOGUy
        roomId: Y2lzY29zcGFyazovL3VzL1JPT00vMGJkYjQwMjAtMTNjNi0xMWU3LWI0MjktZjE3Yjc0ZWFjMjkw

